name: C/C++ CI

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: test
      run: ls
    - name: make
      run: g++ -I"emulator\libs\SDL2-2.26.4\x86_64-w64-mingw32\include\SDL2" -I"emulator\libs\SDL2_image-2.6.3\x86_64-w64-mingw32\include\SDL2" -I"emulator\libs\lua-5.3.6\include" -I"emulator\libs\wineditline-2.206\include" -Wall -pedantic -std=c++2a emulator\src\casioemu.cpp emulator\src\Emulator.cpp emulator\src\Logger.cpp emulator\src\Chipset\CPU.cpp emulator\src\Chipset\CPUPushPop.cpp emulator\src\Chipset\MMURegion.cpp emulator\src\Chipset\CPUControl.cpp emulator\src\Chipset\CPUArithmetic.cpp emulator\src\Chipset\CPULoadStore.cpp emulator\src\Chipset\Chipset.cpp emulator\src\Chipset\MMU.cpp emulator\src\Chipset\InterruptSource.cpp emulator\src\Peripheral\BatteryBackedRAM.cpp emulator\src\Peripheral\Peripheral.cpp emulator\src\Peripheral\Keyboard.cpp emulator\src\Peripheral\Screen.cpp emulator\src\Peripheral\Timer.cpp emulator\src\Peripheral\StandbyControl.cpp emulator\src\Peripheral\ROMWindow.cpp emulator\src\Peripheral\Miscellaneous.cpp emulator\src\Peripheral\BCDCalc.cpp emulator\src\Peripheral\PowerSupply.cpp emulator\src\Peripheral\TimerBaseCounter.cpp emulator\src\Peripheral\RealTimeClock.cpp emulator\src\Peripheral\WatchdogTimer.cpp emulator\src\Peripheral\ExternalInterrupts.cpp emulator\src\Peripheral\IOPorts.cpp emulator\src\Gui\CodeViewer.cpp emulator\src\Gui\Command.cpp emulator\src\Data\ModelInfo.cpp emulator\src\Gui\imgui\imgui_impl_sdl2.cpp emulator\src\Gui\imgui\imgui_impl_sdlrenderer2.cpp emulator\src\Gui\imgui\imgui.cpp emulator\src\Gui\imgui\imgui_widgets.cpp emulator\src\Gui\imgui\imgui_tables.cpp emulator\src\Gui\imgui\imgui_draw.cpp -L"emulator\libs\SDL2-2.26.4\x86_64-w64-mingw32\lib" -L"emulator\libs\SDL2_image-2.6.3\x86_64-w64-mingw32\lib" -L"emulator\libs\lua-5.3.6" -L"emulator\libs\wineditline-2.206\lib64" -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -llua53 -ledit_static -O2 -o casioemu.exe
    
